openapi: 3.2.0
info:
  title: Parcha Get Document API
  description: API to deploy Parcha AI Agents
  version: '1.0'
tags:
- name: GetDocument
paths:
  /getDocument:
    get:
      summary: Get Document
      operationId: get_document_getDocument_get
      parameters:
      - name: expired_url
        in: query
        required: true
        schema:
          type: string
          title: Expired Url
      - name: case_id
        in: query
        required: true
        schema:
          type: string
          title: Case Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - GetDocument
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
