openapi: 3.2.0
info:
  title: Parcha Image Proxy API
  description: API to deploy Parcha AI Agents
  version: '1.0'
tags:
- name: Image Proxy
paths:
  /image-proxy:
    get:
      summary: Get Image
      description: 'Proxy to load an image from an external URL and return the image content.


        Args:

        - url: str : The URL of the image to load.


        Returns:

        - StreamingResponse : The image content streamed back to the client.'
      operationId: get_image_image_proxy_get
      parameters:
      - name: url
        in: query
        required: true
        schema:
          type: string
          title: Url
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Image Proxy
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
