openapi: 3.2.0
info:
  title: Parcha Start Public Job API
  description: API to deploy Parcha AI Agents
  version: '1.0'
tags:
- name: StartPublicJob
paths:
  /api/v1/startPublicJob:
    post:
      summary: Start Public Bdd Job
      description: 'Run KYB Agent Job, specifically our Public BDD job


        This API endpoint starts a job from a specified agent with a command to be executed.


        Args:

        agent_input (AgentJobInputKYB: The model containing the agent key, command, the payload and if you want to run the agent in parallel.

        agent_type (str): The type of the agent (kyb or kyc).

        Returns:

        JobIdResponse: A response object containing the status and job ID.'
      operationId: start_public_bdd_job_api_v1_startPublicJob_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobIdResponse'
      security:
      - HTTPBearer: []
      tags:
      - StartPublicJob
components:
  schemas:
    JobIdResponse:
      properties:
        status:
          type: string
          title: Status
          description: The status of the job
          examples:
          - ok
        job_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Job Id
          description: The unique ID for the job
          examples:
          - job_12345
        job:
          anyOf:
          - type: object
          - type: 'null'
          title: Job
          description: The job object
          examples:
          - id: job_12345
            status: queued
        message:
          type: string
          title: Message
          description: The message related to the job status
          examples:
          - Job enqueued successfully
      type: object
      required:
      - status
      - job_id
      - job
      - message
      title: JobIdResponse
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
