openapi: 3.2.0
info:
  title: Parcha Schemas API
  description: API to deploy Parcha AI Agents
  version: '1.0'
tags:
- name: Schemas
paths:
  /api/v1/agent-schemas/{agent_key}:
    get:
      tags:
      - Schemas
      summary: Get Agent Schemas
      description: 'Get the schema information for all checks in an agent


        This endpoint returns detailed schema information for each check in the specified agent,

        including input and output schemas, check forms, and other metadata.'
      operationId: get_agent_schemas_api_v1_agent_schemas__agent_key__get
      security:
      - HTTPBearer: []
      parameters:
      - name: agent_key
        in: path
        required: true
        schema:
          type: string
          title: Agent Key
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                title: Response Get Agent Schemas Api V1 Agent Schemas  Agent Key  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
